# Generated by Django 3.2.4 on 2021-06-27 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Title')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('text', models.TextField(verbose_name='Description')),
            ],
        ),
    ]
